import React from 'react';

const PageLayout = ({ title, subtitle, children }) => (
    <div style={{ minHeight: '100vh', background: 'var(--color-bg)', color: 'var(--color-text-primary)', paddingBottom: '100px' }}>
        <section style={{ borderBottom: '1px solid var(--color-border)', paddingTop: '40px', background: '#050505' }}>
            <div style={{ maxWidth: '900px', margin: '0 auto', padding: '64px 32px' }}>
                <div className="terminal-label" style={{ marginBottom: '24px', color: 'var(--color-accent)' }}>{subtitle}</div>
                <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(40px, 5vw, 64px)', lineHeight: 0.9, textTransform: 'uppercase', marginBottom: '24px' }}>
                    {title}
                </h1>
            </div>
        </section>
        <section style={{ maxWidth: '900px', margin: '0 auto', padding: '64px 32px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '48px', fontFamily: 'var(--font-sans)', fontSize: '1rem', color: '#bbb', lineHeight: 1.7 }}>
                {children}
            </div>
        </section>
    </div>
);

const Section = ({ title, children }) => (
    <div>
        <h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', color: '#fff', textTransform: 'uppercase', marginBottom: '16px', borderBottom: '1px solid #222', paddingBottom: '8px' }}>
            {title}
        </h2>
        {children}
    </div>
);

export default function SecurityDisclaimer() {
    return (
        <PageLayout title="Security Disclaimer" subtitle="LIMITATIONS OF ANALYSIS">
            
            <div style={{ background: 'rgba(232,24,58,0.05)', borderLeft: '3px solid var(--color-danger)', padding: '24px', marginBottom: '24px' }}>
                <strong style={{ color: 'var(--color-danger)', display: 'block', marginBottom: '12px', fontFamily: 'var(--font-mono)', fontSize: '1rem', textTransform: 'uppercase' }}>
                    Crucial Understanding
                </strong>
                <p style={{ margin: 0, color: '#ccc' }}>
                    The ETH engine performs <strong>analytical threat modeling</strong>. Findings do not always indicate an active, successful compromise of your network.
                </p>
            </div>

            <Section title="1. Inferred Attacker Behavior">
                <p>The core of ETH relies on connecting the dots. If you provide logs showing an exposed RDP port and a lack of Multi-Factor Authentication (MFA), the engine may infer a high risk of Brute Force (T1110) or Ransomware Deployment.</p>
                <p style={{ marginTop: '12px' }}><strong>Remember: Correlation does not equal a confirmed breach.</strong> Just because a vulnerability exists and fits an attacker profile does not mean an attacker has already exploited it.</p>
            </Section>

            <Section title="2. Hypothetical Attack Scenarios">
                <p>Many of the attack phases displayed in the resulting kill chains are <strong>educational and predictive</strong>. They illustrate what an attacker is <em>likely</em> to do next based on your current exposure.</p>
                <ul style={{ listStyleType: 'square', paddingLeft: '24px', marginTop: '12px', color: '#aaa' }}>
                    <li><strong>Attack chains</strong> represent possible paths, not forensic timelines of past events.</li>
                    <li><strong>Risk scoring</strong> reflects the severity of the exposure, not the confirmation of exploitation.</li>
                </ul>
            </Section>

            <Section title="3. Not a Replacement for SIEM/EDR">
                <p>CyberEDT is an exposure intelligence system and learning tool. It is <strong>not</strong> a replacement for deployed Security Information and Event Management (SIEM) systems or Endpoint Detection and Response (EDR) platforms.</p>
                <p style={{ marginTop: '12px' }}>Always cross-reference the predictive models generated by ETH against your actual telemetry in a production SOC environment.</p>
            </Section>
        </PageLayout>
    );
}
