import React from 'react';

const PageLayout = ({ title, subtitle, children }) => (
    <div style={{ minHeight: '100vh', background: 'var(--color-bg)', color: 'var(--color-text-primary)', paddingBottom: '100px' }}>
        <section style={{ borderBottom: '1px solid var(--color-border)', paddingTop: '40px', background: '#050505' }}>
            <div style={{ maxWidth: '900px', margin: '0 auto', padding: '64px 32px' }}>
                <div className="terminal-label" style={{ marginBottom: '24px', color: 'var(--color-accent)' }}>{subtitle}</div>
                <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(40px, 5vw, 64px)', lineHeight: 0.9, textTransform: 'uppercase', marginBottom: '24px' }}>
                    {title}
                </h1>
            </div>
        </section>
        <section style={{ maxWidth: '900px', margin: '0 auto', padding: '64px 32px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '48px', fontFamily: 'var(--font-sans)', fontSize: '1rem', color: '#bbb', lineHeight: 1.7 }}>
                {children}
            </div>
        </section>
    </div>
);

const Section = ({ title, children }) => (
    <div>
        <h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', color: '#fff', textTransform: 'uppercase', marginBottom: '16px', borderBottom: '1px solid #222', paddingBottom: '8px' }}>
            {title}
        </h2>
        {children}
    </div>
);

export default function TermsOfService() {
    return (
        <PageLayout title="Terms of Service" subtitle="CYBEREDT LEGAL">
            <Section title="1. Acceptable Use">
                <p>By accessing the CyberEDT platform and the ETH engine, you agree that it is intended strictly for <strong>educational, defensive cybersecurity, and authorized exposure analysis</strong>.</p>
                <p>You explicitly agree NOT to use CyberEDT for:</p>
                <ul style={{ listStyleType: 'square', paddingLeft: '24px', marginTop: '12px', color: '#aaa' }}>
                    <li>Illegal hacking, unauthorized intrusion, or penetration testing without explicit consent.</li>
                    <li>Developing or deploying malware, ransomware, or exploits.</li>
                    <li>Credential theft, harassment, or illegal surveillance.</li>
                    <li>Any malicious cyber operations against third-party networks.</li>
                </ul>
                <p style={{ marginTop: '16px' }}>Violating these terms will result in immediate termination of access and potential reporting to relevant authorities.</p>
            </Section>

            <Section title="2. Platform Limitation Disclaimer">
                <p>ETH is an <strong>analytical assistance platform</strong>, not a definitive oracle. Outputs generated by the platform may contain inaccuracies, false positives, or incomplete conclusions.</p>
                <ul style={{ listStyleType: 'square', paddingLeft: '24px', marginTop: '12px', color: '#aaa' }}>
                    <li>Attack simulations represent <em>predictive threat models</em>, not confirmed real-world incidents.</li>
                    <li>Hypothetical attack paths illustrate theoretical vulnerabilities based on your inputs.</li>
                    <li>CyberEDT does NOT guarantee breach detection accuracy. You must validate critical findings independently.</li>
                </ul>
            </Section>

            <Section title="3. Limitation of Liability">
                <p>To the maximum extent permitted by applicable law, CyberEDT and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from:</p>
                <ul style={{ listStyleType: 'square', paddingLeft: '24px', marginTop: '12px', color: '#aaa' }}>
                    <li>Misinterpretation of ETH analysis findings.</li>
                    <li>Incorrect remediation actions taken based on platform outputs.</li>
                    <li>Platform downtime, service interruptions, or third-party dependency failures.</li>
                    <li>Operational damages arising from the use or inability to use the platform.</li>
                </ul>
                <p style={{ marginTop: '16px' }}>The platform is provided "AS-IS" with absolutely no warranty of any kind.</p>
            </Section>

            <Section title="4. User Responsibility">
                <p>As a user of the CyberEDT platform, you bear sole responsibility for your actions. You are required to:</p>
                <ul style={{ listStyleType: 'square', paddingLeft: '24px', marginTop: '12px', color: '#aaa' }}>
                    <li>Ensure you have the legal right to upload and analyze any provided logs or telemetry.</li>
                    <li>Remove or redact sensitive secrets, passwords, and classified information before upload.</li>
                    <li>Use the platform only in authorized environments.</li>
                </ul>
            </Section>
        </PageLayout>
    );
}
